name: venderuzmart
description: A new Flutter project.

publish_  to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  intl: ^0.19.0
  lottie: ^3.0.0
  ftoast: ^2.0.0
  get_it: ^7.6.7
  location: ^5.0.3
  geocoding: ^2.1.1
  open_file: ^3.3.2
  fl_chart: ^0.66.1
  auto_route: ^7.8.4
  colornames: ^0.1.0
  geolocator: ^11.0.0
  flutter_svg: ^2.0.9
  google_fonts: ^4.0.4
  sms_autofill: ^2.3.0
  google_place: ^0.4.7
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  video_player: ^2.8.2
  url_launcher: ^6.2.4
  flutter_remix: ^0.0.3
  osm_nominatim: ^2.0.1
  dotted_border: ^2.1.0
  auto_size_text: ^3.0.0
  google_sign_in: ^6.2.1
  flutter_vibrate: ^1.3.0
  pull_to_refresh: ^2.0.0
  flutter_isolate: ^2.0.4
  webview_flutter: ^4.5.0
  flutter_archive: ^6.0.0
  flutter_slidable: ^3.0.1
  phone_text_field: ^0.0.6
  flutter_riverpod: ^2.4.10
  connectivity_plus: ^5.0.2
  percent_indicator: ^4.2.3
  just_the_tooltip: ^0.0.12
  sliding_up_panel: ^2.0.0+1
  freezed_annotation: ^2.4.1
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  easy_date_timeline: ^1.0.5
  permission_handler: ^11.1.0
  flutter_colorpicker: ^1.0.3
  google_maps_flutter: ^2.5.3
  top_snackbar_flutter: ^3.1.0
  proste_indexed_stack: ^0.2.4
  cached_network_image: ^3.3.1
  calendar_date_picker2: ^0.5.5
  flutter_native_splash: ^2.3.10
  flutter_advanced_switch: ^3.1.0
  flutter_time_picker_spinner: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  chewie: ^1.7.4
  readmore: ^2.2.0
  swipe_to: ^1.0.5
  photo_view: ^0.14.0
  grouped_list: ^5.1.2
  data_table_2: ^2.5.11

  #firebase
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  cloud_firestore: ^4.15.6
  firebase_messaging: ^14.7.17
  firebase_dynamic_links: ^5.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.2
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  background_image: 'assets/image/splash.png'

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/image/
    - assets/lottie/
    - assets/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/image/seller.png'
