///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imageAppLogo = 'assets/image/app_logo.png';
  static const String imageMarker = 'assets/image/marker.png';
  static const String imageNoOrders = 'assets/image/no_orders.png';
  static const String imageSalonEmpty = 'assets/image/salon_empty.png';
  static const String imageSeller = 'assets/image/seller.png';
  static const String imageSplash = 'assets/image/splash.png';
  static const String imageStarForBanner = 'assets/image/starForBanner.png';
  static const String lottieClose = 'assets/lottie/close.json';
  static const String lottieEmpty = 'assets/lottie/empty.json';
  static const String lottieEmptyList = 'assets/lottie/empty_list.json';
  static const String lottieEmptyReview = 'assets/lottie/empty_review.json';
  static const String lottieNoItem = 'assets/lottie/noItem.json';
  static const String lottieNotificationEmpty = 'assets/lottie/notification_empty.json';
  static const String lottieProcessing = 'assets/lottie/processing.json';
  static const String svgCalendar = 'assets/svg/calendar.svg';
  static const String svgDelivery = 'assets/svg/delivery.svg';
  static const String svgDiscount = 'assets/svg/discount.svg';
  static const String svgDollarIcon = 'assets/svg/dollar_icon.svg';
  static const String svgHome = 'assets/svg/home.svg';
  static const String svgMenu = 'assets/svg/menu.svg';
  static const String svgNoHome = 'assets/svg/no_home.svg';
  static const String svgOrders = 'assets/svg/orders.svg';
  static const String svgProducts = 'assets/svg/products.svg';
  static const String svgProfile = 'assets/svg/profile.svg';
  static const String svgSearch = 'assets/svg/search.svg';
  static const String svgSelectCalendar = 'assets/svg/select_calendar.svg';
  static const String svgSelectHome = 'assets/svg/select_home.svg';
  static const String svgSelectSearch = 'assets/svg/select_search.svg';
  static const String svgStarForBanner = 'assets/svg/star_for_banner.svg';
  static const String svgWallet = 'assets/svg/wallet.svg';

}
